package org.emunix.unipatcher.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFF795548)
val PrimaryDarkLight = Color(0xFF6B6B6B)
val AccentLight = Color(0xFFFF5252)
val ActivityBackgroundLight = Color(0xFFFFFFFF)
val CardHeaderTextLight = Color(0xFF795548)
val CardLineLight = Color(0xFFE8E8E8)
val CardBackgroundLight = Color(0xFFFFFFFF)
val DrawerTextLight = Color(0x8A000000)
val DrawerSelectedTextLight = Color(0xFFF2777A)
val DrawerSelectorLight = Color(0xFFFFEBEE)
val ToolbarBackgroundLight = Color(0xFFFFFFFF)
val ToolbarTextLight = Color(0xFF000000)
val ToolbarBackArrowLight = Color(0xFF000000)
val TabSelectedTextLight = Color(0xFFFF5252)
val TabIndicatorColorLight = Color(0xFFFF5252)
val DonateButtonLight = Color(0xFFE6921F)

val PrimaryDark = Color(0xFFF2777A)
val PrimaryDarkDark = Color(0xFF2D2D2D)
val AccentDark = Color(0xFFF2777A)
val ActivityBackgroundDark = Color(0xFF2D2D2D)
val CardHeaderTextDark = Color(0xFFCCCCCC)
val CardLineDark = Color(0xFF4B4B4B)
val CardBackgroundDark = Color(0xFF393939)
val DrawerTextDark = Color(0xFFCCCCCC)
val DrawerSelectedTextDark = Color(0xFFE88E88)
val DrawerSelectorDark = Color(0x2CF3E5F5)
val ToolbarBackgroundDark = Color(0xFF393939)
val ToolbarTextDark = Color(0xFFCCCCCC)
val ToolbarBackArrowDark = Color(0xFFCCCCCC)
val TabSelectedTextDark = Color(0xFFF2777A)
val TabIndicatorColorDark = Color(0xFFF2777A)
val DonateButtonDark = Color(0xFFD5A167)
